name: lncmis_mobile_app
description: Lesotho Case Management Mobile Application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  geolocator: ^10.1.0
  shared_preferences: ^2.2.1
  google_fonts: ^6.2.0
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  infinite_scroll_pagination: ^4.0.0
  permission_handler: ^12.0.3
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  excel: ^4.0.6
  rxdart: ^0.28.0
  fluttertoast: ^9.0.0
  collection: ^1.17.1
  new_version_plus: ^0.1.0
  device_info_plus: ^9.1.0
  workmanager: ^0.7.0
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
dependency_overrides:
  win32: ^5.5.4